services:

  kafka-1:
    image: 'apache/kafka:4.2.0'
    container_name: kafka-1
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Define three listeners: Internal, External (Host), and Controller
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:9192,CONTROLLER://:9194
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9092,EXTERNAL://localhost:9192
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9194,2@kafka-2:9294,3@kafka-3:9394
      - KAFKA_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    ports:
      - 9192:9192
    volumes:
      - kafka-1-data:/var/lib/kafka/data

  kafka-2:
    image: 'apache/kafka:4.2.0'
    container_name: kafka-2
    restart: always
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:9292,CONTROLLER://:9294
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:9092,EXTERNAL://localhost:9292
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9194,2@kafka-2:9294,3@kafka-3:9394
      - KAFKA_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    ports:
      - 9292:9292
    volumes:
      - kafka-2-data:/var/lib/kafka/data

  kafka-3:
    image: 'apache/kafka:4.2.0'
    container_name: kafka-3
    restart: always
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:9392,CONTROLLER://:9394
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3:9092,EXTERNAL://localhost:9392
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9194,2@kafka-2:9294,3@kafka-3:9394
      - KAFKA_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    ports:
      - 9392:9392
    volumes:
      - kafka-3-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=test-cluster
      # Since kafka-ui is inside the Docker network, it uses the INTERNAL port (9092)
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    ports:
      - 8081:8080

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
